export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

//user Register
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

//user Login
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

//add Grade
export const ADD_GRADE_BEGIN = "ADD_GRADE_BEGIN";
export const ADD_GRADE_SUCCESS = "ADD_GRADE_SUCCESS";
export const ADD_GRADE_ERROR = "ADD_GRADE_ERROR";

//update Grade
export const UPDATE_GRADE_BEGIN = "UPDATE_GRADE_BEGIN";
export const UPDATE_GRADE_SUCCESS = "UPDATE_GRADE_SUCCESS";
export const UPDATE_GRADE_ERROR = "UPDATE_GRADE_ERROR";

//add Subject
export const ADD_SUBJECT_BEGIN = "ADD_SUBJECT_BEGIN";
export const ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS";
export const ADD_SUBJECT_ERROR = "ADD_SUBJECT_ERROR";

//Get All subjects
export const GET_SUBJECTS_BEGIN = "GET_SUBJECTS_BEGIN";
export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS";
export const GET_SUBJECTS_ERROR = "GET_SUBJECTS_ERROR";

//update subject
export const UPDATE_SUBJECT_BEGIN = "UPDATE_SUBJECT_BEGIN";
export const UPDATE_SUBJECT_SUCCESS = "UPDATE_SUBJECT_SUCCESS";
export const UPDATE_SUBJECT_ERROR = "GUPDATE_SUBJECT_ERROR";

//delete subject
export const DELETE_SUBJECT_BEGIN = "DELETE_SUBJECT_BEGIN";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_ERROR = "DELETE_SUBJECT_ERROR";

//delete grade
export const DELETE_GRADE_BEGIN = "DELETE_GRADE_BEGIN";

//Get All Grades
export const GET_GRADES_BEGIN = "GET_GRADES_BEGIN";
export const GET_GRADES_SUCCESS = "GET_GRADES_SUCCESS";
export const GET_GRADES_ERROR = "GET_GRADES_ERROR";

//Logout user
export const LOGOUT_BEGIN = "LOGOUT_BEGIN";

//Get All Grades
export const GET_ALL_USERS_BEGIN = "GET_ALL_USERS_BEGIN";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR";

//update subject
export const SUBSCRIBE_TEACHER_BEGIN = "SUBSCRIBE_TEACHER_BEGIN";
export const SUBSCRIBE_TEACHER_SUCCESS = "SUBSCRIBE_TEACHER_SUCCESS";
export const SUBSCRIBE_TEACHER_END = "SUBSCRIBE_TEACHER_END";
